services:
  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
      target: dev
    working_dir: /app/apps/api-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./apps/api-gateway:/app/apps/api-gateway:cached
      - ./packages/auth:/app/packages/auth:cached
      - ./tsconfig.base.json:/app/tsconfig.base.json:ro
      - ./.yarn:/app/.yarn:ro
      - ./.yarnrc.yml:/app/.yarnrc.yml:ro
      - ./package.json:/app/package.json:ro
      - ./yarn.lock:/app/yarn.lock:ro
    environment:
      NODE_ENV: development
    command: yarn workspace api-gateway start:dev
